### ISSUE TITLE
refactor bash scripts

### ISSUE THREAD

**Issue by virgilwashere** [ran-dall/mautic-vagrant#1]
Are you interested in updated shell scripts?

    (refactor) 👌 install-mautic.sh

    - [x] ⚡️ improve permission update speed
    - [x] 👌  update ownership and permissions
    - [x] 🔨 refactor with variables
    - [x] 🎨 bash unofficial strict mode

    - [x] 💥 "set -o errexit" is in play

<details><summary>eg: partial diff</summary>

```bash
# "unofficial" bash strict mode
# See: http://redsymbol.net/articles/unofficial-bash-strict-mode
set -o errexit  # Exit when simple command fails               'set -e'
set -o errtrace # Exit on error inside any functions or subshells.
set -o nounset  # Trigger error when expanding unset variables 'set -u'
set -o pipefail # Do not hide errors within pipes              'set -o pipefail'
IFS=$'\n\t'

declare mautic_root='/var/www/mautic'
declare mautic_version='2.15.1'
declare www_user='www-data'

# Fix ownership and permissions of Mautic files
chown -fR "${www_user}":"${www_user}" "${mautic_root}"
find "${mautic_root}" -type d \! -perm /o+x -exec chmod -f 755 '{}' \;
```

</details>

**Comment by ran-dall** [comment]
@virgilwashere Outstanding suggestion! 🔥 Thanks for pointing this out and also sending over the code. That link was eye-opening. If you'd like, you can submit a PR, but I'll also look into this later today. Thanks again! 👍

**Comment by virgilwashere** [comment]
grrr... didnt submit the pr..  my branch is ready..

**Comment by ran-dall** [comment]
@virgilwashere Great work! Finally got a chance to review and merge. 👍 Thanks for your contribution! 🤝
